// File: Greetings.v
// Generated by MyHDL 0.10
// Date: Thu Jun 14 11:31:24 2018


`timescale 1ns/10ps

module Greetings (

);



reg clk2;
reg clk1;
reg [3:0] helloworld0_count;
reg [3:0] helloworld1_count;



initial begin: GREETINGS_CLKDRIVER0_DRIVE_CLK
    while (1'b1) begin
        # 10;
        clk1 <= 1;
        # 10;
        clk1 <= 0;
    end
end


initial begin: GREETINGS_CLKDRIVER1_DRIVE_CLK
    while (1'b1) begin
        # 9;
        clk2 <= 1;
        # 10;
        clk2 <= 0;
    end
end


always @(posedge clk1) begin: GREETINGS_HELLOWORLD0_SAY_HELLO
    $write("Hello count= ");
    $write("%h", helloworld0_count);
    $write("\n");
end


initial begin: GREETINGS_HELLOWORLD0_TEST
    helloworld0_count <= (helloworld0_count + 1);
    @(posedge clk1);
    # 1;
    $write("now= ");
    $write("%h", $time);
    $write(", Test Count = ");
    $write("%h", helloworld0_count);
    $write("\n");
end


always @(posedge clk2) begin: GREETINGS_HELLOWORLD1_SAY_HELLO
    $write("Hello count= ");
    $write("%h", helloworld1_count);
    $write("\n");
end


initial begin: GREETINGS_HELLOWORLD1_TEST
    helloworld1_count <= (helloworld1_count + 1);
    @(posedge clk2);
    # 1;
    $write("now= ");
    $write("%h", $time);
    $write(", Test Count = ");
    $write("%h", helloworld1_count);
    $write("\n");
end

endmodule
