// File: m_ex1.v
// Generated by MyHDL 0.10
// Date: Tue Sep 18 16:43:21 2018


`timescale 1ns/10ps

module m_ex1 (
    clk,
    xyz_x,
    xyz_y,
    xyz_z
);


input clk;
input [7:0] xyz_x;
input [3:0] xyz_y;
output [8:0] xyz_z;
reg [8:0] xyz_z;




always @(posedge clk) begin: M_EX1_HDL
    xyz_z <= (xyz_x + xyz_y);
end

endmodule
